WebApp1.0/Controllers/Master/SubDivController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp1._0.Models;

namespace WebApp1._0.Controllers.Master
{
    
    public class SubDivController : Controller
    {
        private DBContext _db = new DBContext();
        private DBContext obj = new DBContext();
        // GET: SubDiv
        public ActionResult Index()
        {
            try
            {
                DataTable divs = sp.Sp_Generic_Class.GetMultipleRecord("Sp_GetDivisionsResult");
                obj.resultData = divs;

                DataTable subDiv = sp.Sp_Generic_Class.GetMultipleRecord("Sp_GetSubDivResult");
                obj.resultView = subDiv;

                //foreach (DataRow row in divs)
                //{
                //    obj.obj_divResult.Add(new Model_mdivResult
                //    {
                //        divisionid = Convert.ToByte(row["divisionid"]),
                //        divisionname = Convert.ToString(row["divisionname"]),
                //    });
                //}
                //foreach (DataRow rows in subDiv)
                //{
                //    obj.obj_subdivResult.Add(new Model_subDivResult
                //    {
                //        subdivisionid = Convert.ToInt32(rows["subdivisionid"]),
                //        subdivisioncode = Convert.ToInt32(rows["subdivisioncode"]),
                //        subdivisionname = Convert.ToString(rows["subdivisionname"]),
                //        divisionname = Convert.ToString(rows["divisionname"]),
                //    });
                //}
            }
            catch(Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return View(obj);
        }
        [HttpPost]
        public ActionResult SaveSubDiv(Model_msubdivision subdiv)
        {
            try
            {
                if (Request.Form["Save"] == "Save")
                {
                    if (subdiv.subdivisionid == 0)
                    {
                        subdiv.createdby = 1;
                        subdiv.createddate = DateTime.Now;
                        subdiv.modifiedby = 1;
                        subdiv.modifieddate = DateTime.Now;
                        subdiv.active = true;
                        _db.Entry(subdiv).State = System.Data.Entity.EntityState.Added;
                        _db.SaveChanges();
                        if (subdiv.subdivisionid > 0)
                        {
                            obj.usermessage = "Successfully Created Sub Division";
                        }
                    }
                }
                else if (Request.Form["Save"] == "Update")
                {
                    subdiv.modifiedby = 1;
                    subdiv.modifieddate = DateTime.Now;
                    subdiv.createdby = 1;
                    subdiv.createddate = DateTime.Now;
                    subdiv.active = true;
                    _db.Entry(subdiv).State = System.Data.Entity.EntityState.Modified;
                    _db.SaveChanges();
                    if (subdiv.subdivisionid > 0)
                    {
                        obj.usermessage = "Successfully Updated Sub Division";
                    }
                }
                
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult EditSubDiv(int id) 
        {
            DataTable divs = new DataTable();
            try
            {
                if (id > 0)
                {
                    var list = new Dictionary<string, object>();
                    list.Add("SubDivId", id);
                    divs = sp.Sp_Generic_Class.GetMultipleRecordByParam("Sp_GetSubDivOnId", list);
                }
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            obj.resultData = divs;
            return Json(new { obj_subdivs = JsonConvert.SerializeObject(obj.resultData) }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteSubDiv(int id)
        {
            try 
            {
                if(id > 0)
                {
                    var list = new Dictionary<string, object>();
                    list.Add("SubDivId", id);
                    sp.Sp_Generic_Class.GetMultipleRecordByParam("Sp_deleteSubDivOnId", list);
                }
                
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return Json(new { }, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp1.0/Views/SubDiv/Index.cshtml
@model WebApp1._0.Models.DBContext
@using System.Data;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}

<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">

                    <div class="widget flat radius-bordered">
                        <div class="widget-header bg-blue">
                            <span class="widget-caption">Sub-Division</span>
                        </div>
                        <div class="widget-body">
                            <div id="registration-form">
                                <!--<div class="form-title">User Information</div>-->
                                @using (Html.BeginForm("SaveSubDiv", "SubDiv", FormMethod.Post))
                                {
                                    <div class="table-toolbar">
                                        <a id="editabledatatable_new" class="btn btn-success" onclick="addNewRow();">
                                            Add Sub Division
                                        </a>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover" id="simpledatatable">
                                        <thead>
                                            <tr>
                                                <th>Division Name</th>
                                                <th>Sub-Division Code</th>
                                                <th>Sub-Division Name</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (DataRow row in Model.resultView.Rows)
                                            {
                                                <tr id="newRow">
                                                    <input type="hidden" name="subdivisionid" id="subdivisionid" value="" />
                                                    <td>
                                                        <label id="div_name-@row[0]">@row[4]</label>
                                                        <span id="div-@row[0]"></span>
                                                    </td>
                                                    <td id="code-@row[0]">
                                                        <label id="sdcodes-@row[0]">@row[1]</label>
                                                        <input type="hidden" id="hdnsdcodes-@row[0]" value="@row[1]" class="form-control" />
                                                    </td>
                                                    <td id="name-@row[0]">
                                                        <label id="sdname-@row[0]">@row[2]</label>
                                                        <input type="hidden" id="hdnsdname-@row[0]" value="@row[2]" class="form-control" />
                                                    </td>
                                                    <td>
                                                        <span id="editdelete-@row[0]">
                                                            <a class="btn btn-info btn-xs edit" id="edit-@row[0]" onclick="editSubDiv(@row[0]);"><i class="fa fa-edit"></i> Edit</a>
                                                            <a class="btn btn-danger btn-xs delete" id="delete-@row[0]" onclick="deleteSubDiv(@row[0]);"><i class="fa fa-trash-o"></i> Delete</a>
                                                        </span>
                                                        <span id="editCancel-@row[0]">

                                                        </span>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#simpledatatable').DataTable();
        var message = '@Model.usermessage';
        if (message != null && message != "") {
            alert(message);
        }
    });
    function editSubDiv(id) {
        $.ajax({
            type: "post",
            url: '@Url.Action("EditSubDiv", "SubDiv")',
            data: { id: id },
            datatype: "json",
            success: function (data) {
                if (data.obj_zone != '') {
                    if (data.obj_subdivs != '') {
                        $(".edit").attr("disabled", "disabled");
                        $("#editCancel-" + id).html("");
                        $("#subdivisionid").val(id);
                        $("#div-" + id).html("");
                        $("#div-" + id).append('<select name="ref_divisionid" id="ref_divisionid-' + id + '" class="form-control" required><option value="">Select Corporate</option>@foreach(DataRow corp in Model.resultData.Rows){<option value="@corp[0]">@corp[2]</option>}</select>').show();
                        $("#div_name-" + id).css("display", "none");
                        $.each($.parseJSON(data.obj_subdivs), function (key, value) {
                            $("#sdcodes-" + id).css("display", "none");
                            $("#hdnsdcodes-" + id).attr("type", "text");
                            $("#hdnsdcodes-" + id).attr("name", "zonecode");
                            $("#sdname-" + id).css("display", "none");
                            $("#hdnsdname-" + id).attr("type", "text");
                            $("#hdnsdname-" + id).attr("name", "zonename");
                            $("#editCancel-" + id).append('<input type="submit" value="Update" name="Save" id="edits-'+id+'" class="btn btn-success btn-xs save" /> <a class="btn btn-warning btn-xs" id="cancels-' + id + '" cancel" onclick="replaceRow(' + id + ');"><i class="fa fa-times"></i> Cancel</a>').show();
                            $("#editdelete-"+id).css("display","none");
                            $('#ref_divisionid-' + id + ' option[value=' + value.ref_divisionid + ']').prop("selected", "selected");
                        });
                    }
                }
            }
        });
    }

    function deleteSubDiv(id) {
        alert("Do you really want to delete this record ?")
        $.ajax({
            type: "post",
            url: '@Url.Action("DeleteSubDiv", "SubDiv")',
            data: { id: id },
            datatype: "json",
            success: function (data) {
                alert("Record successfully deleted");
                location.reload();
            }
        });
    }

    function addNewRow() {
        $("#newRow").html("");
        var appData = '';
        appData = '<td><select name="ref_divisionid" id="ref_divisionid" class="form-control" required><option value="">Select Division</option>@foreach(DataRow corp in Model.resultData.Rows){<option value="@corp[0]">@corp[2]</option>}</select></td>' +
                  '<td><input type="text" name="subdivisioncode" id="subdivisioncode" placeholder="Sub Division Code" class="form-control" required/></td>' +
                  '<td><input type="text" name="subdivisionname" id="subdivisionname" placeholder="Sub Division Name" class="form-control" required/></td>' +
                  '<td><input type="submit" value="Save" class="btn btn-success btn-xs save" name="Save" /> <a class="btn btn-warning btn-xs cancel" onclick="removeRow();"><i class="fa fa-times"></i> Cancel</a></td>';

        $("#newRow").append(appData);
        $("#newRow").css("display", "table-row");
    }

    function removeRow() {
        $("#newRow").css("display", "none");
    }

    function replaceRow(id) {
        $(".edit").removeAttr("disabled", "disabled");
        $("#ref_divisionid-" + id).css("display", "none");
        $("#div_name-" + id).css("display", "block");

        $("#hdnsdcodes-" + id).attr("type", "hidden");
        $("#sdcodes-" + id).css("display", "block");

        $("#hdnsdname-" + id).attr("type", "hidden");
        $("#sdname-" + id).css("display", "block");

        $("#editCancel-" + id).css("display", "none");
        $("#editdelete-" + id).css("display", "block");
    }
</script>