WebApp1.0/Controllers/Master/DivisionController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp1._0.Models;

namespace WebApp1._0.Controllers.Master
{
    public class DivisionController : Controller
    {
        private DBContext _db = new DBContext();
        private DBContext obj = new DBContext();
        // GET: Division
        public ActionResult Index()
        {
            try
            {
                DataTable circle = sp.Sp_Generic_Class.GetMultipleRecord("Sp_getCircleDetails");
                obj.resultData = circle;

                DataTable divRes = sp.Sp_Generic_Class.GetMultipleRecord("Sp_GetDivisionsResult");
                obj.resultView = divRes;

                ////Mapper.CreateMap<User,UserDto >();  
                //foreach (DataRow row in circle)
                //{
                //    obj.obj_circlrResult.Add(new Model_mcircleResult
                //    {
                //        circleid = Convert.ToByte(row["circleid"]),
                //        circlename = Convert.ToString(row["circlename"]),
                //    });
                //}
                //foreach (DataRow div in divRes)
                //{
                //    obj.obj_divResult.Add(new Model_mdivResult
                //    {
                //        divisionid = Convert.ToByte(div["divisionid"]),
                //        divisioncode = Convert.ToByte(div["divisioncode"]),
                //        divisionname = Convert.ToString(div["divisionname"]),
                //        circlename = Convert.ToString(div["circlename"]),
                //    });
                //}
            }
            catch(Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return View(obj);
        }
        [HttpPost]
        public ActionResult SaveDiv(Model_mdivision div)
        {
            try
            {
                if (Request.Form["Save"] == "Save")
                {
                    if (div.divisionid == 0)
                    {
                        div.createdby = 1;
                        div.createddate = DateTime.Now;
                        div.active = true;
                        _db.Entry(div).State = System.Data.Entity.EntityState.Added;
                        _db.SaveChanges();
                        if (div.divisionid > 0)
                        {
                            obj.usermessage = "Successfully Created Division";
                        }
                    }
                }
                else if (Request.Form["Save"] == "Update")
                {
                    div.modifiedby = 1;
                    div.modifieddate = DateTime.Now;
                    div.createdby = 1;
                    div.createddate = DateTime.Now;
                    div.active = true;
                    _db.Entry(div).State = System.Data.Entity.EntityState.Modified;
                    _db.SaveChanges();
                    if (div.divisionid > 0)
                    {
                        obj.usermessage = "Successfully Updated Section";
                    }
                }
                
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult EditDivision(int id) 
        {
            DataTable div = new DataTable();
            try
            {
                if (id > 0)
                {
                    var list = new Dictionary<string, object>();
                    list.Add("divId", id);
                    div = sp.Sp_Generic_Class.GetMultipleRecordByParam("Sp_GetDivOnId", list);
                }
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }

            obj.resultData = div;
            return Json(new { obj_div = JsonConvert.SerializeObject(obj.resultData) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteDiv(int id)
        {
            try
            {
                if (id > 0)
                {
                    var list = new Dictionary<string, object>();
                    list.Add("divId", id);
                    sp.Sp_Generic_Class.GetMultipleRecordByParam("Sp_DeleteDivOnId", list);
                }
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return Json(new { },JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp1.0/Views/Division/Index.cshtml
@model WebApp1._0.Models.DBContext
@using System.Data;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <div class="widget flat radius-bordered">
                        <div class="widget-header bg-blue">
                            <span class="widget-caption">Division</span>
                        </div>
                        <div class="widget-body">
                            <div id="registration-form">
                                <!--<div class="form-title">User Information</div>-->
                                @using (Html.BeginForm("SaveDiv", "Division", FormMethod.Post))
                                {
                                    <div class="table-toolbar">
                                        <a id="editabledatatable_new" class="btn btn-success" onclick="addNewRow();">
                                            Add Division
                                        </a>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover" id="simpledatatable">
                                        <thead>
                                            <tr>
                                                <th>Circle Name</th>
                                                <th>Division Code</th>
                                                <th>Division Name</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                                
                                            @foreach (DataRow rows in Model.resultView.Rows)
                                            {
                                                <tr id="newRow">
                                                    <input type="hidden" name="divisionid" id="divisionid" value="" />
                                                    <td>
                                                        <label id="cir_name-@rows[0]">@rows[4]</label>
                                                        <span id="circle-@rows[0]"></span>
                                                    </td>
                                                    <td id="code-@rows[0]">
                                                        <label id="dcodes-@rows[0]">@rows[1]</label>
                                                        <input type="hidden" id="hdndcodes-@rows[0]" value="@rows[1]" class="form-control" />
                                                    </td>
                                                    <td id="name-@rows[0]">
                                                        <label id="dname-@rows[0]">@rows[2]</label>
                                                        <input type="hidden" id="hdndname-@rows[0]" value="@rows[2]" class="form-control" />
                                                    </td>
                                                    <td>
                                                        <span id="editdelete-@rows[0]">
                                                            <a class="btn btn-info btn-xs edit" id="edit-@rows[0]" onclick="editdivision(@rows[0]);"><i class="fa fa-edit"></i> Edit</a>
                                                            <a class="btn btn-danger btn-xs delete" id="delete-@rows[0]" onclick="deleteDiv(@rows[0]);"><i class="fa fa-trash-o"></i> Delete</a>
                                                        </span>
                                                        <span id="editCancel-@rows[0]">

                                                        </span>
                                                    </td>
                                                </tr>
                                                i++;
                                            }
                                        </tbody>
                                    </table>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#simpledatatable').DataTable();
        var message = '@Model.usermessage';
        if (message != null && message != "") {
            alert(message);
        }
    });
    function editdivision(id) {
        $.ajax({
            type: "post",
            url: '@Url.Action("EditDivision", "Division")',
            data: { id: id },
            datatype: "json",
            success: function (data) {
                if (data.obj_div != '') {
                    $(".edit").attr("disabled", "disabled");
                    $("#editCancel-" + id).html("");
                    $("#divisionid").val(id);
                    $("#circle-" + id).html("");
                    $("#circle-" + id).append('<select name="ref_circleid" id="ref_circleid-' + id + '" class="form-control" required><option value="">Select Corporate</option>@foreach(DataRow corp in Model.resultData.Rows){<option value="@corp[0]">@corp[2]</option>}</select>').show();
                    $("#cir_name-" + id).css("display", "none");
                    $.each($.parseJSON(data.obj_div), function (key, value) {
                        $("#dcodes-" + id).css("display", "none");
                        $("#hdndcodes-" + id).attr("type", "text");
                        $("#hdndcodes-" + id).attr("name", "zonecode");
                        $("#dname-" + id).css("display", "none");
                        $("#hdndname-" + id).attr("type", "text");
                        $("#hdndname-" + id).attr("name", "zonename");
                        $("#editCancel-" + id).append('<input type="submit" value="Update" name="Save" id="edits-'+id+'" class="btn btn-success btn-xs save" /> <a class="btn btn-warning btn-xs" id="cancels-' + id + '" cancel" onclick="replaceRow(' + id + ');"><i class="fa fa-times"></i> Cancel</a>').show();
                        $("#editdelete-"+id).css("display","none");
                        $('#ref_circleid-' + id + ' option[value=' + value.ref_circleid + ']').prop("selected", "selected");
                    });
                }
            }
        });
    }
    function deleteDiv(id) {
        alert("Do you really want to delete this record ?")
        $.ajax({
            type: "post",
            url: '@Url.Action("DeleteDiv", "Division")',
            data: { id: id },
            datatype: "json",
            success: function (data) {
                alert("Record successfully deleted");
                location.reload();
            }
        });
    }

    function addNewRow() {
        $("#newRow").html("");
        var appData = '';
        appData = '<td><select name="ref_circleid" id="ref_circleid" class="form-control" required><option value="">Select Circle</option>@foreach(DataRow corp in Model.resultData.Rows){<option value="@corp[0]">@corp[2]</option>}</select></td>' +
                  '<td><input type="text" name="divisioncode" id="divisioncode" placeholder="Division Code" class="form-control" required/></td>' +
                  '<td><input type="text" name="divisionname" id="divisionname" placeholder="Division Name" class="form-control" required/></td>' +
                  '<td><input type="submit" value="Save" class="btn btn-success btn-xs save" name="Save" /> <a class="btn btn-warning btn-xs cancel" onclick="removeRow();"><i class="fa fa-times"></i> Cancel</a></td>';

        $("#newRow").append(appData);
        $("#newRow").css("display", "table-row");
    }

    function removeRow() {
        $("#newRow").css("display", "none");
    }
    function replaceRow(id) {
        $(".edit").removeAttr("disabled", "disabled");
        $("#ref_circleid-" + id).css("display", "none");
        $("#cir_name-" + id).css("display", "block");


        $("#hdndcodes-" + id).attr("type", "hidden");
        $("#dcodes-" + id).css("display", "block");

        $("#hdndname-" + id).attr("type", "hidden");
        $("#dname-" + id).css("display", "block");

        $("#editCancel-" + id).css("display", "none");
        $("#editdelete-" + id).css("display", "block");
    }
</script>