WebApp1.0/Controllers/Master/ZoneController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp1._0.Models;

namespace WebApp1._0.Controllers.Master
{
    public class ZoneController : Controller
    {
        private DBContext _db = new DBContext();
        private DBContext obj = new DBContext();
        // GET: Master
        public ActionResult Index()
        {
            try
            {
                DataTable corp = sp.Sp_Generic_Class.GetMultipleRecord("Sp_GetCorporate");
                obj.resultData = corp;
                DataTable zdata = sp.Sp_Generic_Class.GetMultipleRecord("Sp_getZoneDetails");
                obj.resultView = zdata;

                //foreach (DataRow row in corp)
                //{
                //    obj.obj_corporate.Add(new Model_mcorporate
                //    {
                //        corporateid = Convert.ToByte(row["corporateid"]),
                //        corporatename = Convert.ToString(row["corporatename"]),
                //    });
                //}
                //foreach (DataRow rows in zdata)
                //{
                //    obj.obj_zoneResult.Add(new Model_mzoneResult
                //    {
                //        zoneid = Convert.ToByte(rows["zoneid"]),
                //        zonecode = Convert.ToByte(rows["zonecode"]),
                //        zonename = Convert.ToString(rows["zonename"]),
                //        corporatename = Convert.ToString(rows["corporatename"]),

                //    });
                //}
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return View(obj);
        }

        [HttpPost]
        public ActionResult SaveZone(Model_mzone z) 
        {
            try
            {
                if (Request.Form["Save"] == "Save")
                {
                    if (z.zoneid == 0)
                    {
                        z.createdby = 1;
                        z.createddate = DateTime.Now;
                        z.active = true;
                        _db.Entry(z).State = System.Data.Entity.EntityState.Added;
                        _db.SaveChanges();
                        if (z.zoneid > 0)
                        {
                            obj.usermessage = "Successfully Created Zone";
                        }
                    }
                }
                else if (Request.Form["Save"] == "Update")
                {
                    z.modifiedby = 1;
                    z.modifieddate = DateTime.Now;
                    z.createdby = 1;
                    z.createddate = DateTime.Now;
                    z.active = true;
                    _db.Entry(z).State = System.Data.Entity.EntityState.Modified;
                    _db.SaveChanges();
                    if (z.zoneid > 0)
                    {
                        obj.usermessage = "Successfully Updated Zone";
                    }
                }
                
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult EditZone(int id)
        {
            DataTable zone = new DataTable();
            try
            {
                var list = new Dictionary<string, object>();
                list.Add("zoneId", id);
                zone = sp.Sp_Generic_Class.GetMultipleRecordByParam("Sp_GetZoneOnId", list);
            }
            catch (Exception ex)
            {
                obj.usermessage = ex.Message;
                Console.Write(ex.Message);
            }
            obj.resultData = zone;
            return Json(new { obj_zone = JsonConvert.SerializeObject(obj.resultData) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteZone(int id)
        {
            var list = new Dictionary<string, object>();
            list.Add("zoneId", id);
            sp.Sp_Generic_Class.GetMultipleRecordByParam("Sp_deleteZoneOnId", list);
            return Json(new { }, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp1.0/Views/Zone/Index.cshtml
@model WebApp1._0.Models.DBContext
@using System.Data;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<div class="page-body">
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-xs-12">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <div class="widget flat radius-bordered">
                        <div class="widget-header bg-blue">
                            <span class="widget-caption">Zone</span>
                        </div>
                        <div class="widget-body">
                            <div id="registration-form">
                                <!--<div class="form-title">User Information</div>-->
                               @using (Html.BeginForm("Savezone", "Zone", FormMethod.Post))
                               {
                                    <div class="table-toolbar">
                                        <a id="editabledatatable_new" class="btn btn-success" onclick="addNewRow();">
                                            Add New Zone
                                        </a>
                                    </div>
                                    <table class="table table-striped table-bordered table-hover" id="simpledatatable">
                                        <thead>
                                            <tr>
                                                <th>Corporate</th>
                                                <th>Zone Code</th>
                                                <th>Zone Name</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>

                                        <tbody id="newRow">
                                            @foreach (DataRow row in Model.resultView.Rows)
                                            {
                                                <tr>
                                                    <input type="hidden" name="zoneid" id="zoneid" value="" />
                                                    <td>
                                                        <label id="corp_name-@row[0]">@row[4]</label>
                                                        <spanid id="corp-@row[0]"></spanid>
                                                    </td>
                                                    <td id="code-@row[0]">
                                                        <label id="zcodes-@row[0]">@row[1]</label>
                                                        <input type="hidden" id="hdnzcodes-@row[0]" value="@row[1]" class="form-control" />
                                                    </td>
                                                    <td id="name-@row[0]">
                                                        <label id="zname-@row[0]">@row[2]</label>
                                                        <input type="hidden" id="hdnzname-@row[0]" value="@row[2]" class="form-control" />
                                                    </td>
                                                    <td>
                                                        <span id="editdelete-@row[0]">
                                                            <a class="btn btn-info btn-xs edit" id="edit-@row[0]" onclick="editZone(@row[0]);"><i class="fa fa-edit"></i> Edit</a>
                                                            <a class="btn btn-danger btn-xs delete" id="delete-@row[0]" onclick="deleteZone(@row[0]);"><i class="fa fa-trash-o"></i> Delete</a>
                                                        </span>
                                                        <span id="editCancel-@row[0]">

                                                        </span>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#simpledatatable').DataTable();
        var message = '@Model.usermessage';
        if (message != null && message != "") {
            alert(message);
        }


        $('#basicBootstrapForm').bootstrapValidator({
            framework: 'bootstrap',
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                zonecode: {
                    row: '.col-xs-4',
                    validators: {
                        notEmpty: {
                            message: 'The first name is required'
                        }
                    }
                }
            }
        });
    });
    function editZone(id) {
        $.ajax({
            type: "post",
            url: '@Url.Action("EditZone", "Zone")',
            data: { id: id },
            datatype: "json",
            success: function (data) {
                if (data.obj_zone != '') {
                    $(".edit").attr("disabled", "disabled");
                    $("#editCancel-" + id).html("");
                    $("#zoneid").val(id);
                    $("#corp-" + id).html("");
                    $("#corp-" + id).append('<select name="ref_corporateid" id="ref_corporateid-' + id + '" class="form-control" required><option value="">Select Corporate</option>@foreach(DataRow corp in Model.resultData.Rows){<option value="@corp[0]">@corp[2]</option>}</select>').show();
                    $("#corp_name-" + id).css("display", "none");
                    $.each($.parseJSON(data.obj_zone), function (key, value) {
                        $("#zcodes-" + id).css("display", "none");
                        $("#hdnzcodes-" + id).attr("type", "text");
                        $("#hdnzcodes-" + id).attr("name", "zonecode");
                        $("#zname-" + id).css("display", "none");
                        $("#hdnzname-" + id).attr("type", "text");
                        $("#hdnzname-" + id).attr("name", "zonename");
                        $("#editCancel-" + id).append('<input type="submit" value="Update" name="Save" id="edits-'+id+'" class="btn btn-success btn-xs save" /> <a class="btn btn-warning btn-xs" id="cancels-' + id + '" cancel" onclick="replaceRow(' + id + ');"><i class="fa fa-times"></i> Cancel</a>').show();
                        $("#editdelete-"+id).css("display","none");
                        $('#ref_corporateid-' + id + ' option[value=' + value.ref_corporateid + ']').prop("selected", "selected");
                    });
                }
            }
        });
    }
    function deleteZone(id) {
        alert("Do you really want to delete this record ?")
        $.ajax({
            type: "post",
            url: '@Url.Action("DeleteZone", "Zone")',
            data: { id: id },
            datatype: "json",
            success: function (data) {
                alert("Record successfully deleted");
                location.reload();
            }
        });
    }

    function addNewRow() {
        //$("#newRow").html("");
        var appData = '';
        appData = '<tr>'+
                  '<td><select name="ref_corporateid" id="ref_corporateid" class="form-control" required><option value="">Select Corporate</option>@foreach(DataRow corp in Model.resultData.Rows){<option value="@corp[0]">@corp[2]</option>}</select></td>' +
                  '<td><input type="text" name="zonecode" id="zonecode" placeholder="Zone Code" class="form-control" data-bv-notempty="true"  data-bv-notempty-message="The first name is required and cannot be empty" /></td>' +
                  '<td><input type="text" name="zonename" id="zonename" placeholder="Zone Name" class="form-control" required/></td>' +
                  '<td><input type="submit" value="Save" class="btn btn-success btn-xs save" name="Save" /> <a class="btn btn-warning btn-xs cancel" onclick="removeRow();"><i class="fa fa-times"></i> Cancel</a></td>'+
                  '</tr>';
        $('#newRow tr:first').before(appData);

    }

    function removeRow() {
        $("#newRow").css("display", "none");
    }
    function replaceRow(id) {
        $(".edit").removeAttr("disabled", "disabled");
        $("#ref_corporateid-" + id).css("display", "none");
        $("#corp_name-" + id).css("display", "block");

        $("#hdnzcodes-" + id).attr("type", "hidden");
        $("#zcodes-" + id).css("display", "block");

        $("#hdnzname-" + id).attr("type", "hidden");
        $("#zname-" + id).css("display", "block");
        
        $("#editCancel-" + id).css("display", "none");
        $("#editdelete-" + id).css("display", "block");
    }
</script>